### PR TITLE
#1386: Add "empty states" component (closes #1386)

### LINKED ISSUE #1386: Add "empty states" component
As per the guidelines and design defined by @alessandravilla in https://github.com/buildo/issues/issues/799

- create new component in BRC
- [add examples and guidelines ](https://paper.dropbox.com/doc/Empty-states--AoFegf9XgM8pvV3yYWtWRLenAg-ks6uBIJYVm4ZaKPNmRCE5)

### PR DESCRIPTION
**Pull request by ecamellini**
Closes #1386

## Test Plan

image

### CODE REVIEW

**Comment by ecamellini** [comment]
@giogonzo @alessandravilla should I also add the guidelines README? English or Italian? Also, what should I do with the paper document after we merge this?

https://paper.dropbox.com/doc/Empty-states--AoYE40Ps4f937XUou_KXkcmvAg-ks6uBIJYVm4ZaKPNmRCE5

**Comment by ecamellini** [comment]
Perfect, allora traduco, metto qua nel README, e depreco il paper direi.

**Comment by alessandravilla** [comment]
Non riesco a fare preview pr, guardando l'immagine che hai caricato direi di:
- cambiare font weight del title in bold
- mettere il primary style al btn
- aumentare un po' i padding tra i componenti
image

**Comment by ecamellini** [comment]
@giogonzo @alessandravilla addressed comments and added README, in English. It should be ready to be merged 🎉

**Pull request merged**
