### PR TITLE
#280: [Button] no check before invoke setState() for still mounted component (closes #280)

### LINKED ISSUE #280: [Button] no check before invoke setState() for still mounted component
## description
Sometimes buttons, e.g.: Save for comment in sample details throw a warning when clicked.
Check against still mounted component with isMounted() is an antipattern, so a proper solution is to make the promise cancelable, although the warning seems caused by doResetInternalState() call.

## how to reproduce
- Have a button which `onClick` cause a re-render

## specs
- check component is still **mounted** when `setState` is called after the `onClick` promise resolution.

## misc
[optional: other useful info]

### PR DESCRIPTION
**Pull request by ascariandrea**
Issue #280

As pointed out [here](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html) I made the `onClick` returning promise cancelable.

### CODE REVIEW

**Comment by giogonzo** [comment]
as pointed out here https://github.omnilab.our.buildo.io/buildo/labonline/issues/1159#issuecomment-4843 , no need to introduce the concept of "cancelable promise" just for this button..

I'm more for: track the mount status in a  `_isMounted` or similar property on the component instance. Should be a three lines addition..

(also: travis complains!)

**Comment by FrancescoCioria** [comment]
> (also: travis complains!)

`Button` has tests. @ascariandrea you should probably update them

**Comment by ascariandrea** [comment]
@FrancescoCioria yep I fixed them!
@giogonzo I think as long our problem is related to **promises** we should stick to this `makeCancelable` implementation.

**Comment by giogonzo** [comment]
@ascariandrea my opinion is: this problem is not related to promises in any way, but instead to any async thing we might be doing in a component. Fixing/changing the fact that promises are non-cancelable looks out of scope to me, and also this fixes it for this component only..

quick poll @buildo/frontend , opinions?

**Pull request closed without merging**
