### PR TITLE
#850: Dropdown: no style for focus (closes #850)

### LINKED ISSUE #850: Dropdown: no style for focus
## description
Border-color should change when the dropdown is focused

## how to reproduce
- focus on a dropdown

## specs
- Add a new variable: `$border-color-focused` (with default value `$waterBlue`) and use it when needed

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by veej**
Closes #850

### tests performed
- when focused hitting TAB

- when disabled, border doesn't change on focus

- [x] Google Chrome
- [x] Internet Explorer

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@veej have you verified that when the dropdown is open `$border-color-open` beats `$border-color-focus`?

**Comment by francescogior** [comment]
@FrancescoCioria it does
image

**Comment by FrancescoCioria** [comment]
> this should be considered breaking, what do you think?

If I'm not wrong, In the original paper written by alessandra the focus was there which means that this is a simple defect.
Nevertheless, as we've kept this defect for maaaaaaany months it may be one of those cases where it's better to upgrade it to "breaking".

**Comment by veej** [comment]
> @veej have you verified that when the dropdown is open $border-color-open beats $border-color-focus?

@FrancescoCioria yep

> this should be considered breaking, what do you think?

@francescogior same old doubt. This could be considered a defect (`react-select` has a style for focus), but yeah, for anyone who doesn't want a style for focus this is potentially breaking.
Btw I won't use `$border-color` as default value, since default values should follow our guidelines.

**Comment by francescogior** [comment]
> Btw I won't use $border-color as default value, since default values should follow our guidelines.

Right. Then breaking and devs should take care to backport this on relevant projects

**Pull request merged**
