### PR TITLE
#50: create Scrollable wrapper component (closes #50)

### LINKED ISSUE #50: create Scrollable wrapper component
requirements:
- [x] accept function content callback as `children`
  - [x] pass `scrollTo` function to callback
    - args: (x, y, time)
    - should also work on mobile
- [x] wrap content in `div` (so as usual accept `className`, `style`, `id`)
- [x] stop scroll event propagation (optional)
- [x] scroll should work properly on mobile
  - enable gravity scroll for iOS by default
- [ ] customizable scrollbar (also optional)
- [x] support every scroll direction (`overflow`)
  - only x
  - only y
  - both (default)

/cc @giogonzo @francescogior

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #50

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
actually @giogonzo wait until i fix `stopPropagation` not working with touch events (mobile)

**Comment by FrancescoCioria** [comment]
@giogonzo done

**Comment by giogonzo** [comment]
wow, almost a month ago :skull: 

@FrancescoCioria just rebased, should be ready to merge. Any more changes to add here?

**Comment by FrancescoCioria** [comment]
no, it should be fine. you can merge it

**Comment by giogonzo** [comment]
didn't update examples and bundle though

**Pull request merged**
