### PR TITLE
#724: Dropdown: text color should not change on hover (closes #724)

### LINKED ISSUE #724: Dropdown: text color should not change on hover
## description
Right now, when hovering over a dropdown with a value selected, the text color changes to a lighter gray.

Using the default style, we want it to remain unchanged, and change only the background color.
It must still be possible to change the hover color via the `$text-color-hover` variable.

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
- change the default value for `$text-color-hover` to be equal to `$text-color`

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by sawsanias**
Closes #724 

**test plan**

- Go to dropDown menu component
- Try to select one of the options in one of the dropDown menu
- Hover over the dropdown, the text color of the **SELECTED VALUE** should **NOT** be changed, as the attached gif:

cksrp6lsoj

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@sawsanias we probably forgot to tell you that we slightly changed the review flow in buildo about 2 weeks ago :)

when you have time you should read [this chapter](https://buildo.gitbooks.io/book/content/workflow/3.pull-requests.html) in our book, especially [the PR workflow](https://buildo.gitbooks.io/book/content/workflow/3.pull-requests.html#the-pr-workflow) section

**Comment by sawsanias** [comment]
@FrancescoCioria  I updated the TP

**Comment by veej** [comment]
Wait... looking the solution and reading the issue again there's something I'm not convinced of... in this way the `$text-color-hover` variable turns to be completely useless.
I think the issue was more about changing the default style, leaving the ability to change the hover color when needed. My fault, the issue is not completely clear.
@francescogior, what do you think?

**Comment by francescogior** [comment]
it's clear now! ok @sawsanias ?

**Comment by veej** [comment]
Issue updated! ;)

**Pull request merged**
