### PR TITLE
dropdown - selectAll option handling

### LINKED ISSUE #947: Dropdown: SelectAll in multi mode
## requirements
- When dropdown is in `multi` mode, it should be possible to add an "all" option that allows to select all the options at once.
- The "All" option can't be selected along with other options: when "all" is selected, it should be the only selected value (this means that all the previously selected options must be cleared), and the dropdown should have the style of a single-value selection (i.e. `All` shouldn't be shown as a tag)
- When `all` is selected, it should be possible to select any other value. When this happens, the new value should replace "all"

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by Cardu**
Closes #947

⚠️  Not ready to merge, just a prototype to show the idea

### CODE REVIEW

**Comment by Cardu** [comment]
Alternative implementation that I was talking about on slack: https://buildo.slack.com/archives/C289TFRAQ/p1568460163000100?thread_ts=1568380065.007700&cid=C289TFRAQ

**Comment by Cardu** [comment]
Tested customizing the example dropdown like this:

```
initialState = {};

const onChange = value => value === 'all' ? setState({ value: {value: 'all', label: "tutti quanti"} }) : setState({ value });

const options = [
  { value: "apple", label: "Apple" },
  { value: "avocado", label: "Avocado" },
  { value: "orange", label: "Orange" },
  { value: "lemon", label: "Lemon" },
  { value: "mandarin", label: "Mandarin" }
];

console.debug(state);

<Dropdown
	showSelectAll
    selectAllLabel='selezionami tutto'
  type="single"
  value={state.value}
  onChange={onChange}
  placeholder="Select some fruit"
  options={options}
/>;
```

**Comment by fes300** [comment]
@Cardu can we close this?

**Comment by Cardu** [comment]
@fes300  nope! ⚠️  this branch was just a demonstration and it should be deleted, I think @veej  is working on the "good" version of this

**Pull request closed without merging**
