### PR TITLE
#404: [tests] add tests back on CI (closes #404)

### LINKED ISSUE #404: [tests] add tests back on CI
## requirements
as per title, they are currently disabled and in need of fixes

### PR DESCRIPTION
**Pull request by giogonzo**
Issue #404

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@giogonzo I fixed tests, but CI keeps failing

**Comment by giogonzo** [comment]
I see, it is a long standing issue, @gabro could know something more about it

these are possibly related:
https://github.com/este/este/issues/812
https://github.com/CrabDude/babel-node-debug/issues/7

but I don't see a clear fix there, confused

**Comment by FrancescoCioria** [comment]
@gabro can you help me fix this issue? (`npm test` locally but not on CI)

this PR is based on #452

**Comment by gabro** [comment]
god dog: http://www.guyellisrocks.com/2015/11/babel-cannot-read-property-error-of.html

trying to fix this

**Comment by gabro** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

also, if you read the commit message...

**Pull request merged**
