### PR TITLE
#714: [Tablo Perf] handle hover style for rows in CSS (closes #714)

### LINKED ISSUE #714: [Tablo Perf] handle hover style for rows in CSS
← #711

## requirements
`onRowMouseEnter/Leave` callbacks are heavy form a perf point-of-view as they're called twice for each row when users scroll with the mouse pointer above `Tablo`.

As they're used mostly (always so far) to change the background color of a row when hovered, we should handle this simple case in the CSS so to ensure users use them only when really necessary.

## specs
- change the background color of a row when hovered in the CSS
- add a sass variable for it

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #714

### tests performed
- hover a row in `default` example
  - row background is colored correctly
- select a row and hover it
  - row background is set to the hover one (hover beats select)
- pass `onRowMouseEnter` and `onRowMouseLeave` to `Tablo`
  - correctly called when entering/leaving a row

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
because selected color is applied only if row is not hovered:
```scss
&.selected:not(:hover) .public_fixedDataTableCell_main {
```

so yeah, it doesn't beat it, it's selected which is disabled when row is hovered

**Comment by francescogior** [comment]
Yes sure! But I was discussing
- why one should beat the other one by default (before it was the opposite I guess, and it'd apply as well)
- above all, how to make the user able to customize it?

**Comment by francescogior** [comment]
As discussed offline, using a sass variable `hovered-seelexted-row` (default set to `hovered-row` or `selected-row`)or something may be a good idea

**Comment by FrancescoCioria** [comment]
@francescogior done. TestPlan remained valid after the change

**Pull request merged**
