### PR TITLE
#159: add `MoreOrLess` from labonline (closes #159)

### LINKED ISSUE #159: add `MoreOrLess` from labonline
#156 

this is the original component: https://github.omnilab.our.buildo.io/buildo/labonline/tree/master/web/src/app/components/Basic/MoreOrLess

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #159

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@giogonzo tested in LOL: should be ready to merge

**Comment by giogonzo** [comment]
:+1:

**Comment by giogonzo** [comment]
:+1: but still missing tests!

**Comment by FrancescoCioria** [comment]
@giogonzo

**Pull request merged**
