### PR TITLE
#764: Use babel-preset-buildo (closes #764)

### LINKED ISSUE #764: Use babel-preset-buildo
## requirements
reduce the effort of keep up-to-date babel presets and plugins using `babel-preset-buildo` instead

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by ascariandrea**
Issue #764 

### tests performed
`npm run start` ✔️ 
`npm run build` ✔️ 

                              
- [ ] Google Chrome
- [ ] Internet Explorer

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
> Yep, but it seems related to babel-plugin-lodash in react-flexview lodash/babel-plugin-lodash#83

@ascariandrea it worked fine before your PR

**Comment by ascariandrea** [comment]
@FrancescoCioria Since I've removed the `babel-plugin-lodash` from the `devDependencies` the `build-showroom` fails because `babel` uses the `.babelrc` found in the required folders (when present).
That's why it works on `master`, but `react-flexview` needs to be fixed.

**Comment by ascariandrea** [comment]
@FrancescoCioria Now that `react-flex-view` has been fixed the tests pass 😎

**Comment by FrancescoCioria** [comment]
tested, seems fine 👍 
@veej can you complete your review?

**Pull request merged**
