### PR TITLE
#1035: [Typo] Initial setup (closes #1035)

### LINKED ISSUE #1035: [Typo] Initial setup
← #1034

## requirements
{describe the new feature}

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by veej**
Closes #1035

### tests performed
- [x] showroom works
- [x] build works
- [x] AlinityPRO works with new build

and all three keep working from #1041 branch! (so they work when `src` has one or more `.tsx?` files)

- [ ] Google Chrome
- [ ] Internet Explorer

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@veej It finally works! the commit history is horrible, but who cares...
in the end I made it work by making both `typescript` and `babel` transpile every file both in the build and in webpack... it's not a great solution, I know, but it works :P

UPDATE: ups, the tests are still failing...

**Comment by ascariandrea** [comment]
Shouldn't the lodash imports case be fixed also in `package.json`?

**Comment by FrancescoCioria** [comment]
> Shouldn't the lodash imports case be fixed also in package.json?

what do you mean? they are correct in the `package.json`: they should all be in lowercase

**Comment by ascariandrea** [comment]
It's confusing the different case in `import` and *dependencies* in `package.json`.
Won't the `import` fail for case sensitive os?

**Comment by FrancescoCioria** [comment]
> It's confusing the different case in import and dependencies in package.json.
Won't the import fail for case sensitive os?

can you make an example? I really don't understand: I fixed every case error of `lodash` and the CI (which is case sensitive) is passing. Which code are you reading?

**Comment by ascariandrea** [comment]
My bad 🙈 
I was looking at the previous case instead the fixed one 😅

**Pull request merged**
