### PR TITLE
#462: add popover style prop (closes #462)

### LINKED ISSUE #462: Add popover style prop
## description
- There's no way to pass style to the `popover` wrapper

## specs
- add `style` to `popover` prop struct
- pass it to the `<div>` wrapper in `getPopoverTemplate` method

### PR DESCRIPTION
**Pull request by francescogior**
Issue #462

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@francescogior is this PR/Issue still valid?

**Comment by francescogior** [comment]
I think it is, but looking rapidly at the code I think the diff isn't solving #462 intent

**Comment by FrancescoCioria** [comment]
@francescogior you commits are fine, but the code you modified is very obsolete (even if merge isn't blocked for some reason). please rebase on master (NB: it might be easier to copy-paste your changes)

**Comment by francescogior** [comment]
@FrancescoCioria rebased

**Comment by FrancescoCioria** [comment]
💯

**Pull request merged**
